# projeto do arquivo do workflow do git 
name: TI222
on: 
  push:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambientes"
        type: choice
        required: true
        default: dev
        options: 
          - dev
          - main

jobs:
  informacao:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar a estrutura de diretorio
        run: ls -la 
      - name: Obtem codigo do projeto do repositorio
        uses: actions/checkout@v3
      - name: Mostrar a estrutura da diretorio atualizada
        run: |
          echo "Estrutura do repositorio : "
          ls -la
          echo "exemplo de listar um diretorio"
          ls -la api || echo"não existe um diretorio"

